name: Build RStudio Server and push to Docker Hub

# from https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
on: 
  push:
    branches: ['main', 'dev']
    tags:
      - 'v*'
    paths:
      - 'rstudio/Dockerfile'
  pull_request:
    branches: ['main', 'dev']
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: victor2wy/rbiotechsalary
          tags: |
            type=raw,value=latest,enable={{is_default_branch}} # set latest tag for default branch
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./rstudio
          file: ./rstudio/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}